debug: true
server:
  port: 80
  servlet:
    context-path: /
     
spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/sales
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: YOUR_FACEBOOK_APP_ID
          clientSecret: YOUR_FACEBOOK_APP_SECRET
          scope:
           - email
           - public_profile      